#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.

menuentry "Shutdown Now" {
	echo "Shutting down..."
	halt
}

menuentry "Reboot" {
	echo "Rebooting..."
	reboot
}

if [ ${grub_platform} == "efi" ]; then
	menuentry "Reboot with EFI_OS_INDICATIONS_BOOT_TO_FW_UI" --id "uefi-firmware" {
		echo "Rebooting with EFI_OS_INDICATIONS_BOOT_TO_FW_UI..."
		fwsetup
	}
else
	menuentry "Reboot with EFI_OS_INDICATIONS_BOOT_TO_FW_UI (Not Available)" --id "uefi-firmware" {
		echo "Fallback: Rebooting"
		reboot
	}
fi

